services:
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: readers
      POSTGRES_USER: readers
      POSTGRES_DB: readers
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672" # Puerto AMQP
      - "15672:15672" # UI de administración
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  db_data:
  rabbitmq_data:
